### ISSUE TITLE
BUG: break fontawesome

### ISSUE THREAD

**Issue by matte78** [jcwillox/lovelace-paper-buttons-row#11]
last update (0.1.2) break integration with fontawesome

**Comment by jcwillox** [comment]
Hey, please elaborate on what the actual issue is are the icons not showing up?
In that case its likely that the font awesome integration needs to be updated for 0.110 as there is a breaking in change in how Home Assistant loads custom iconsets. 
Basically if the icons are not working with the native HA elements (e.g. sensor rows etc.) then it's an issue with fontawesome.

**Comment by matte78** [comment]
sorry, removed and reinstalled again, now work :-(
