### ISSUE TITLE
Feature Request: in-line jinja2 or javascript

### ISSUE THREAD

**Issue by roopesh** [jcwillox/lovelace-paper-buttons-row#9]
I would like to be able to execute some logic while rendering attributes... in particular style, but I can imagine it for any attribute of the card.

My current example is that I have a ceiling fan that only publishes state as On or Off. I can get the speed from the attribute `state_attr("<fan entity>", "speed")`.  I have a row of buttons for High, Medium, Low, and Off.  I can't figure out how to highlight the right one since it's not at the state, but if I could update style dynamically I could apply the right style to the right button.

**Comment by uvjim** [comment]
I have a similar request actually.
I'm using a Logitech Harmony and would like to be able to have a button row for calling a service that would start an Activity.  That is easily done.  However, I would like to show which is the current activity using a style.  The activity is stored in an attribute (current_activity) rather than the state of the remote.

**Comment by ktownsend-personal** [comment]
Showing an attribute would be very useful for me as well. Rather than worry about jninja2 or javascript, many other elements I have seen simply have an attribute property. Maybe that can be added to this element?

**Comment by jcwillox** [comment]
This has been fixed in release [0.5.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/0.5.0).
